# Package Overview
package_name: survival_model

# Data Files
training_data_file: survival.csv
test_data_file: test.csv

# Variables
# The variable we are attempting to predict (Survival)
target: DEATH_EVENT

pipeline_name: survival_model
pipeline_save_file: survival__model_output_v

features:
  - age
  - anaemia
  - creatinine_phosphokinase
  - diabetes
  - ejection_fraction
  - high_blood_pressure
  - platelets
  - serum_creatinine
  - serum_sodium
  - sex
  - smoking
  - time

# Features names

age_var: age
anaemia_var: anaemia
creatinine_phosphokinase_var: creatinine_phosphokinase
diabetes_var: diabetes
ejection_fraction_var: ejection_fraction
high_blood_pressure_var: high_blood_pressure
platelets_var: platelets
serum_creatinine_var: serum_creatinine
serum_sodium_var: serum_sodium
sex_var: sex
smoking_var: smoking
time_var: time
  
# set train/test split
test_size: 0.20

# to set the random seed
random_state: 42
# alogrithm parameters
n_estimators: 200
max_depth: 4
max_leaves: 5